### PR TITLE
Create website-bug.md

### PR DESCRIPTION
**Pull request by darkknight443**

### CODE REVIEW

**Review by 9glenda — CHANGES_REQUESTED** [review]
should be assigned to  @Niteletsplay

**Comment by 9glenda** [comment]
yes

**Comment by darkknight443** [comment]
sorry for including your name and mail in the commit message i tried to make the commit co authored by you but I did fail

**Comment by 9glenda** [comment]
no problem it doesn't have to be coauthored. I didn't really help anyway

**Review by 9glenda — APPROVED** [review]

**Pull request merged**
